name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: bundle install
        run: bundle install
      - name: Run tests
        run: rails test
      - name: Run linter
        run: rake standard
