name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.18
      - name: Run tests
        run: bin/rails test
      - name: Run linter
        run: bin/rake standard
